patreon: andrey_helldar
tidelift: "packagist/andrey-helldar/laravel-json-response"
open_collective: "laravel-json-response"
custom: [ "https://paypal.me/helldar", "https://yoomoney.ru/to/410012608840929" ]
